import type { Metadata } from "next";
import Link from "next/link";
import { Geist, Geist_Mono, Roboto } from "next/font/google";
import "./globals.css";
import { FaToriiGate } from "react-icons/fa6";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const robotoSans = Roboto({
  weight: ["400", "700"],
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { isLoggedIn } from "./login/lib/auth";
import { getAccountInfo } from "./login/lib/tmdb";

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  const {username} = await getAccountInfo()
  

  return (
    <html lang="en">
      <body
        className={`${robotoSans.className} antialiased bg-[url('/images/pattern3.jpg')] bg-[length:600px_600px]`}
      >
        <div className="flex justify-between py-8 px-12 font-semibold text-white bg-sky-900/[0.5] sticky top-0">
          <Link href="/login">{username?`${username}`:"Iniciar Sesion"}</Link>
          <Link href="/" className="text-4xl flex">
            <span className="text-blue-300">青</span>
            <span className="text-green-300">緑</span>
            <FaToriiGate />
            </Link>
          <Link href="/vistos">Lista de Vistos</Link>
        </div>
        {children}
      </body>
    </html>
  );
}
